name: 'sample'
description: 'sample gh action that run scanner to detect runtime/framework'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3      
    - uses: actions/setup-node@v3
      with:
        node-version: '12.x'
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'       
    - uses: actions/setup-python@v4
      with:
        python-version: '3.7'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'   
    - id: runner        
      run: | 
        chmod +x ${{ github.action_path }}/build/runner
        ${{ github.action_path }}/build/runner -app="app_id" -desc="short desc of my good app"
      shell: bash
