name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - name: Install dependencies
        run: |
          cd scan
          go get .
      - name: Build
        run: |
          cd scan
          go build -o ./../build/scan
      - name: Push binary
        run: |
          git config --global user.name "actionsbot"
          git config --global user.name "actionsbot"
          git pull 
          git add .
          git status
          git commit -m "actions bot pushing binary for scan"
          git push
