name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - name: Install dependencies
        run: cd scan && go get .
      - name: Build
        run: cd scan && go build -o ../scan
      - name: push code
        run: |
          git config --global user.name "actionsbot"
          git config --global user.name "rhnshiva@gmail.com"
          git add .
          git push
