name: Go
on:
  push:
    branches:
      - main
    paths-ignore: 
      - 'build/**'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - name: gooos
        shell: bash
        run: echo $GOOS $GOARCH
      - name: Install dependencies
        run: |
          cd scan
          go get .
      - name: Build
        run: |
          cd scan
          go build -o ./../build/scan
      - name: Push binary
        if: github.event_name == 'push'
        run: |
          git config --global user.name "actionsbot"
          git config --global user.email "actionsbot@github.com"
          git commit -a -m "actions bot pushing binaries"
          git push
